# Generated by Django 4.2.11 on 2026-03-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
