[example]
exten => _XXXXXXXXXX,1,Answer()
	same => n,NoOp(Call Answered ${SIP_HEADER(From)})
	same => n,NoOp(Caller NUMBER ${ACCOUNTCODE})
	same => n,Set(TIMEOUT(absolute)=180)
	same => n,NoOp(Disposition - ${CDR(disposition)})
	same => n,NoOp(Channel - ${CDR(channel)})
	same => n,NoOp(Destination - ${CDR(dst)})
	same => n,NoOp(Destinatin Channel - ${CDR(dstchannel)})
	same => n,NoOp(Call Start Time - ${CDR(start)})
	same => n,NoOp(Call End Time - ${CDR(end)})
	same => n,NoOp(Call Duration ${CDR(duration)})
	same => n,NoOp(BillSec - ${CDR(billsec)})
	same => n,NoOp(UniqueId - ${CDR(uniqueid)})
	same => n,NoOp(AMAFlags - ${CDR(amaflags)})
	same => n,Set(CHANNEL(LANGUAGE)=en)
	same => n,Set(AGI_MOBILE_NUMBER=${EXTEN})
	same => n,Set(PLAYBACK_PATH=/var/lib/asterisk/sounds/custom/${CDR(dst)})
	same => n,Set(CHANNEL(hangup_handler_push)=hangup-handler,s,1)
	same => n,GoTo(100001-on-answer,s,1)
	
[100001-on-answer]
exten => s,1,NoOp(On Answered called)
	same => n,Playback(/var/lib/asterisk/sounds/custom/1)
	;${PLAYBACK_PATH}
	same => n,GoTo(100001-on-answer-1.1,s,1)
	
[100001-on-answer-1.1]
exten => s,1,Set(REPEAT_COUNT=$[${IF($[${REPEAT_COUNT}]?${REPEAT_COUNT}:0}+1)])
	same => n,Background(/var/lib/asterisk/sounds/custom/1.1)
	same => n,WaitExten(3)
	same => n,Background(/var/lib/asterisk/sounds/custom/nokeypress)
	same => n,Background(/var/lib/asterisk/sounds/custom/1.1)
	same => n,WaitExten(3)
	
exten => 1,1,NoOp(User pressed 1)
	same => n,Playback(/var/lib/asterisk/sounds/custom/2)
	same => n,AGI(dtmf.py,1002,1,${AGI_MOBILE_NUMBER})
	same => n,Hangup()
		
exten => 2,1,NoOp(User pressed 2)
	same => n,GoTo(100001-option-2,s,1)
	
exten => 3,1,NoOp(User pressed 3)
	same => n,Playback(hello-world)
	same => n,Hangup()
	
exten => 0,1,GoTo(100001-on-answer-1.1,s,1)

exten => i,1,NoOp(Invalid option)
	same => n,Playback(invalid)
	same => n,Hangup()
	
exten => t,1,NoOp(${CDR(billsec)})
	same => n,Hangup()
	
	
[100001-option-2]
exten => s,1,NoOp(Option 2 pressed)
	same => n,Playback(/var/lib/asterisk/sounds/custom/3)
	same => n,GoTo(1000001-option-2.1,s,1)
	
	
[1000001-option-2.1]
exten => s,1,NoOp(Option 2.1 pressed)
	same => n,Background(/var/lib/asterisk/sounds/custom/3.1)
	same => n,WaitExten(3)
	
exten => 1,1,NoOp(User pressed 1 in option 2)
	same => n,GoTo(100001-option-2.1-1,s,1)
	
	
[100001-option-2.1-1]
exten => s,1,Playback(/var/lib/asterisk/sounds/custom/4)
	same => n,Hangup()
	
	
[hangup-handler]
exten => s,1,NoOp(Call hungup by user ${CDR(billsec)})
